# Imports

In [1]:
import numpy as np
import pandas as pd
import pickle
import torch

# Open

In [2]:
pickle_path = "exports/name_to_index"

with open(pickle_path, "rb") as f:   # "rb" = read binary
    name_to_index = pickle.load(f)

name_to_index

{300968622: 0,
 301309622: 1,
 301314150: 2,
 301314154: 3,
 301314208: 4,
 301318641: 5,
 331662668: 6,
 331662717: 7,
 331999156: 8,
 331999213: 9,
 332003372: 10,
 332003629: 11,
 332003730: 12,
 332003895: 13,
 332003899: 14,
 332007728: 15,
 332008063: 16,
 332008082: 17,
 332340127: 18,
 332340236: 19,
 332344539: 20,
 332344592: 21,
 332344670: 22,
 332344760: 23,
 332344908: 24,
 332349228: 25,
 332349327: 26,
 332353106: 27,
 332353336: 28,
 332353438: 29,
 332353566: 30,
 332685594: 31,
 332685751: 32,
 332685755: 33,
 332689776: 34,
 332690153: 35,
 333030976: 36,
 333031114: 37,
 333035349: 38,
 333039671: 39,
 354775482: 40,
 354779890: 41,
 362689128: 42,
 362693077: 43,
 362693473: 44,
 362697657: 45,
 362701764: 46,
 362701875: 47,
 362701895: 48,
 362701969: 49,
 363029976: 50,
 363030024: 51,
 363030040: 52,
 363034174: 53,
 363034211: 54,
 363034407: 55,
 363034501: 56,
 363038752: 57,
 363038831: 58,
 363042781: 59,
 363047222: 60,
 363370708: 61,
 363370913: 62,
 3

In [3]:
pickle_path = "exports/connectivity_matrix"

with open(pickle_path, "rb") as f:   # "rb" = read binary
    connectivity_matrix = pickle.load(f)

connectivity_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1927, 1927))

In [4]:
(connectivity_matrix>=1)*1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1927, 1927))

In [5]:
rand_same_shape = torch.randn((1927, 1927))
rand_same_shape

tensor([[ 0.2859, -1.6683, -0.8370,  ..., -1.4059,  0.0313,  0.7054],
        [-0.8029,  0.0670,  0.2696,  ...,  1.5510,  0.0556,  0.7555],
        [ 1.0389, -0.9624, -0.0721,  ...,  2.0913,  0.3560,  1.0917],
        ...,
        [ 0.2567, -1.0500,  0.8013,  ..., -0.5597,  1.0207, -0.3559],
        [ 2.0418, -1.4944, -0.1159,  ...,  0.1455, -0.2814, -0.6231],
        [ 2.4859,  1.6011,  0.1006,  ...,  0.3618, -1.6996, -0.2975]])

# Create a network

In [6]:
from recurrent_network import Recurrent_Network

In [7]:
# what do we need to define a recurrent network?

# the random PN to KC connections
# the KC self connections alongside their weights
# the mode of APL normalisation

# I think I should pass in the weights directly so I can create and store them outside of class.
# I need weights for PN to KC and then KC to KC. I will think of APL later.

In [8]:
n_PN = 100
n_KC = 1927

# random PN -> KC weights
W = torch.rand(n_PN, n_KC)  # values in [0, 1]

# random KC recurrent weights
R = torch.rand(n_KC, n_KC)  # values in [0, 1]

In [9]:
net = Recurrent_Network(n_PN=100, n_KC=1927, W=W, R=R)

# Try it

In [10]:
x = torch.rand(n_PN)
y = net.forward(x)
y.shape

torch.Size([1927])

In [11]:
X = torch.rand(100, n_PN)
KCseq = net.run_sequence(X)
KCseq

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         7.6513e-01],
        [1.3541e+02, 4.9029e+01, 4.1829e+02,  ..., 3.8323e+02, 0.0000e+00,
         1.0624e+02],
        [1.1360e+05, 7.4572e+04, 4.2578e+05,  ..., 3.7828e+05, 0.0000e+00,
         6.0450e+04],
        ...,
        [       nan,        nan,        nan,  ...,        nan,        nan,
                nan],
        [       nan,        nan,        nan,  ...,        nan,        nan,
                nan],
        [       nan,        nan,        nan,  ...,        nan,        nan,
                nan]], grad_fn=<CatBackward0>)

the infinities show up because values explode

In [12]:
KCseq.shape

torch.Size([100, 1927])